# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c1d6ab4314d3075961ac77253558f9b41207653d5c19d0fda34c3b061cb57a89102b03b7283db0c85fdac43f23976487467d0978e7c90531efec1ca6a0ee121
  aws:
    access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

test:
  secret_key_base: 3b4cba75124895063fe386d0351ca0aec609a2df576d47597e5857e2e5c1fba9f29cacb8ebdaab15c6a3fca28e7ec3e21b87b58972e11399820ea75d8f250b22
  aws:
    access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  # Having a single access token should be good enough for now,
  # as this API is not intended to be used by different clients (for now)
  access_token: <%= ENV["ACCESS_TOKEN"] %>
  aws:
    access_key_id: <%= ENV["AWS_ACCESS_KEY_ID"] %>
    secret_access_key: <%= ENV["AWS_SECRET_ACCESS_KEY"] %>
